name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: golang-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: make
